package main

func importNames() []string {
	return []string{"Kyiv",
		"Kharkiv",
		"Lviv",
		"Odesa",
		"Dnipro",
		"Donetsk",
		"Zaporizhia",
		"Kryvyi Rih",
		"Mykolaiv",
		"Mariupol",
		"Lutsk",
		"Chernivtsi",
		"Poltava",
		"Sumy",
		"Kherson",
		"Vinnytsia",
		"Khmelnytskyi",
		"Chernihiv",
		"Rivne",
		"Ternopil",
		"Ivano-Frankivsk",
		"Uzhhorod",
		"Bila Tserkva",
		"Kremenchuk",
		"Kropyvnytskyi",
		"Melitopol",
		"Mukachevo",
		"Cherkasy",
		"Sloviansk",
		"Boryspil",
		"Severodonetsk",
		"Brovary",
		"Kamianets-Podilskyi",
		"Berdyansk",
		"Nikopol",
		"Kovel",
		"Drohobych",
		"Zhovkva",
		"Kramatorsk",
		"Khust",
		"Pryluky",
		"Stryi",
		"Shostka",
		"Yevpatoria",
		"Balaklava",
		"Fastiv",
		"Nizhyn",
		"Korsun-Shevchenkivskyi",
		"Izyum",
		"Bakhmut"}
}

func findInNames(name string) int {
	names := []string{"Kyiv",
		"Kharkiv",
		"Lviv",
		"Odesa",
		"Dnipro",
		"Donetsk",
		"Zaporizhia",
		"Kryvyi Rih",
		"Mykolaiv",
		"Mariupol",
		"Lutsk",
		"Chernivtsi",
		"Poltava",
		"Sumy",
		"Kherson",
		"Vinnytsia",
		"Khmelnytskyi",
		"Chernihiv",
		"Rivne",
		"Ternopil",
		"Ivano-Frankivsk",
		"Uzhhorod",
		"Bila Tserkva",
		"Kremenchuk",
		"Kropyvnytskyi",
		"Melitopol",
		"Mukachevo",
		"Cherkasy",
		"Sloviansk",
		"Boryspil",
		"Severodonetsk",
		"Brovary",
		"Kamianets-Podilskyi",
		"Berdyansk",
		"Nikopol",
		"Kovel",
		"Drohobych",
		"Zhovkva",
		"Kramatorsk",
		"Khust",
		"Pryluky",
		"Stryi",
		"Shostka",
		"Yevpatoria",
		"Balaklava",
		"Fastiv",
		"Nizhyn",
		"Korsun-Shevchenkivskyi",
		"Izyum",
		"Bakhmut"}
	for i := range names {
		if names[i] == name {
			return i
		}
	}
	return -1
}
